# -*- coding: utf-8 -*-
"""1_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dm7hbD03mCCbg8ypeH9xJD9Qeclf-urA

# * Topics Covered
1. OBJECTS
2. VARIABLES
3. FUNCTION

# OBJECTS : THE DATA RECORD
Iska matlab hai object ke andar data hota hai — jaise fields ya attributes.

OBJECT: A data record with fields, an instance of a class.
"""

Salary = 10000

100000

Salary

print(Salary)

print

"""# Type: defines the type of data.
        eg. int, str

        type(variable)**bold text**
"""

type('sam')

type(1000)

"""# VARIABLES
Variables: A DEFINED NAME THAT REFERENCE AN OBJECT.
"""

Job_title =" data analyst"
job_location="america"
job_salary=90000

id(Job_title),id(job_location)

job_1="da"
job_2="da"
job_3="daa"

id(job_1),id(job_2),id(job_3)
#different variable with same string still have diff id

job_2=job_1

id(job_2),id(job_1)
#same id will be displayed as job_2=job_1

"""#Functions: The Manipulators of Objects
Function: A reusable piece of code that perform a specific task.

**DEFINED BY "def"**
"""

def greet():
  return "Sam the great hiker"

greet()

Job_title =" data analyst"
job_location="america"
job_salary=90000

def display(location,salary,title):
  return print(f"Location: {location}\n Title:{title}\n Salary: ${salary} ")

display(job_location,job_salary,Job_title)

#PASCAL TRIANGLE
def pascal(n):
  for i in range(n):
    num=1
    print(" "*(n-i),end='')
    for j in range(i+1):
        print(num,end=' ')
        num=num*(i-j)//(j+1)
    print()

row=int(input())
pascal(row)

"""# class
class: a template for creating objects(records)
"""